name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build executable
        run: nix build .#cardano-n2n-client
      - name: Build docker image
        run: nix build .#docker-image -o output-docker-image
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cardano-n2n-client-image
          path: ./output-docker-image
      - name: Build arx
        run: nix bundle -o output-linux-tarball
      - name: Upload tarball Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cardano-n2n-client
          path: ./output-linux-tarball
  unit:
    name: Run unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run Tests
        working-directory: .
        run: nix run .#cardano-n2n-client-tests
  # bench:
  #   name: Run Benchmarks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: cachix/install-nix-action@v31
  #       with:
  #         extra_nix_config: |
  #           trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  #           substituters = https://cache.iog.io https://cache.nixos.org/
  #           accept-flake-config = true
  #     - uses: cachix/cachix-action@v15
  #       with:
  #         name: paolino
  #         authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  #     - name: Run Benchmarks
  #       run: nix run .#bench
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check Formatting
        run: nix develop .#quality -c just format
      - name: Check linting
        run: nix develop .#quality -c just hlint
